### ISSUE TITLE
Feature Request: Does this support OTP field?

### ISSUE THREAD

**Issue by curtainp** [chrisgrieser/alfred-pass#6]
### Feature Requested

Thank you for developing this excellent workflow, I'd like to ask that the OTP field is supported now or is there a plan to follow up with support?

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
There is currently no OTP support. You mean with [pass-otp](https://github.com/tadfisher/pass-otp#readme) I assume?

Since I am neither using the feature myself, and since it's an extension for `pass` (meaning far fewer people will use it), I am afraid I don't have any plans to add support for that in the foreseeable future.

**Comment by tmerten** [comment]
Sorry for necromancing this @chrisgrieser but before I open a PR I wanted to check what you'd like to merge the most. I see three solutions for this:

1. (what I did in my setup, see attached screenshot) is duplicating the `search passwords` script filter as `otp`, piping it to a script that runs `pass otp` instead of `pass search` and piping that to the same output
2. re-use the existing script filter to call `pass-otp` with yet another shortcut (e.g. `shift+cmd`), less duplication but user needs to remember the shortcut
3. (hardest, most fragile IMO) adding a stage that inspects the password from the `copy pw` script, checking if it e.g. starts with `otpauth://` and then running the [logic from `pass otp`](https://github.com/pass-extension/pass-otp/blob/7bb50dbc4b6073f12f40be66a5ee371b9652a646/otp.bash#L331) to grab the otp code instead of copying the result

If you're open for 1. or 2. I'm happy to open a PR :).

<img width="703" height="354" alt="Image" src="https://github.com/user-attachments/assets/ad7be712-f8f4-4ff2-8285-da09ff85b9cc" />

**Comment by chrisgrieser** [comment]
I am open to a PR, but the problem is that I do not use pass-otp myself or even otp tokens. So it's hard for me to assess which solution makes the most sense. 

You can open a draft PR and we can discuss this there? Would be helpful if you outlined how pass-otp works (Do pass entries habe an extra field for it, or are there extra entries? What does the user need to know to use otps? etc)
